name: Java CI with Maven

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build test Docker image
        if: runner.os == 'Linux'
        run: |
          docker build -t mokojarasi/test-python-sshd:latest src/test/docker/
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          version: '25.0.2'
          components: 'python'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Build and Test
        run: mvn -B verify
      - name: Upload test results to Codecov
        if: runner.os == 'Linux'
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./target/surefire-reports/
      - name: Build Native Image
        run: mvn -Pnative native:compile
